Repository OCA/repo-maintainer-conf, pull requests merged in 2025-02, with the labels that each got.

#68 sale-blanket: add new repo and psc
  conf/psc/sale.yml
  conf/repo/sale.yml
Labels: approved

#66 [ADD] Logistics: Release Channel, Reservation and Shopfloor repositories
  conf/repo/logistics.yml
Labels: approved, ready to merge

#70 [ADD] Shopflor app repo + PSC
  conf/psc/shopfloor-app.yml
  conf/repo/shopfloor.yml
Labels: approved

#74 Add mass-mailing repo
  conf/repo/mass-mailing.yml
Labels: approved

#75 [ADD] JordiBForgeFlow as l10n-usa maintainer
  conf/psc/l10n.yml
  conf/repo/l10n.yml
Labels: approved

#76 [IMP] repo/l10n.yml: Bump Mexico default to 18.0
  conf/repo/l10n.yml
Labels: needs review
