Repository OCA/repo-maintainer-conf, pull requests merged in 2025-06, with the labels that each got.

#92 Change queue default branch to 18.0
  conf/repo/queue.yml
Labels: approved, needs review

#94 Add AI repositories and PSC
  conf/psc/ai.yml
  conf/repo/ai.yml
Labels: approved

#100 [ADD] Proposal new repository Complaint and Infringement Management (CIM)
  conf/psc/cim.yml
  conf/repo/cim.yml
Labels: approved, ready to merge
